language: node_js
install: "npm install"
before_script: "./node_modules/.bin/cake test-prepare"
script: "npm test"
node_js:
  - 0.4
  - 0.6
  - 0.8
  - 0.9
notifications:
  irc:
    - "irc.freenode.org#bevry-dev"
  email:
    recipients:
      - travis@bevry.me